# Site settings
title: Hairuo's github pages
description: "A blog about math, stats, and science"
github_username: hairuo
minimal_mistakes_skin: "dark"

# Theme
remote_theme: mmistakes/minimal-mistakes

# Markdown & Math
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge

mathjax:
  enable: true
  tex:
    inlineMath: [['$', '$'], ['\\(', '\\)']]
    displayMath: [['$$', '$$'], ['\\[', '\\]']]

# Defaults
defaults:
  # Posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

# Include pages & includes
include: ["_pages", "_includes"]

# Comments via Giscus
comments:
  provider: "giscus"
  giscus:
    repo: "hairuo/hairuo.github.io"
    repo_id: "R_kgDOQBs5tQ"
    category: "Comments"
    category_id: "DIC_kwDOQBs5tc4Cwo9a"
    mapping: "pathname"
    strict: "0"
    reactions_enabled: "1"
    emit_metadata: "0"
    input_position: "bottom"
    theme: "preferred_color_scheme"
    lang: "en"
